### ISSUE TITLE
v 0.19 dropped counties?

### ISSUE THREAD

**Issue by mlissner** [yaph/geonamescache#11]
I hope this wasn't intentional, but when I upgraded to the 0.19 version, the us_counties information disappeared. The latest code has it, but the version on pip doesn't?

**Comment by yaph** [comment]
No not intentional, I'll check it.

**Comment by yaph** [comment]
That's very strange when I build a distribution locally the us_counties.json file is included in both the tar archive and the wheel.

**Comment by yaph** [comment]
I released v0.20 which contains the us_counties.json. Still don't know what went wrong with 0.19. Thanks for the catch!
