### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by dulrich15** [yaph/geonamescache#12]
Getting a UnicodeDecodeError when trying to install with Python 3.5.

Thanks,
Dave

**Comment by yaph** [comment]
Hmm, I've used geonamescache in Python 3.5.1 environments and just did a successful test installation. What OS are you using?

**Comment by dulrich15** [comment]
Ubuntu 14.04 using Anaconda 4.0.0 with Python 3.5.1

I was trying to install using `pip install geonamescache` since I couldn't find it with `conda`.

```
Collecting geonamescache
  Using cached geonamescache-0.21.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-s7wdt12s/geonamescache/setup.py", line 9, in <module>
        license = f.read()
      File "/home/dave/anaconda3/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 30: ordinal not in range(128)
```

**Comment by yaph** [comment]
The latest release should fix this problem.

**Comment by mudrila** [comment]
Meet same problem when I try to install this package via `pip` or `pip3`.
