### ISSUE TITLE
Convert README from restructured text to markdown

### ISSUE THREAD

**Issue by yaph** [yaph/geonamescache#23]

**Comment by mlissner** [comment]
This surprises me. I don't think Pypi supports markdown, last I checked, so we're all stuck using rst. I think!

**Comment by yaph** [comment]
You can use markdown when you add the keyword argument `long_description_content_type='text/markdown'` to the `setup` function in `setup.py`, like in this file https://github.com/yaph/logya/blob/master/setup.py

**Comment by mlissner** [comment]
Woah! That's great.
