### ISSUE TITLE
Various fields should be an int or float

### ISSUE THREAD

**Issue by mlissner** [yaph/geonamescache#8]
In the cities database a bunch of fields are provided as strings. Can we convert these to an int? 

For example: 

    {u'countrycode': u'US',
     u'geonameid': u'5385955',
     u'latitude': u'34.1064',
     u'longitude': u'-117.59311',
     u'name': u'Rancho Cucamonga',
     u'population': u'165269',
     u'timezone': u'America/Los_Angeles'},

Of these, geonameid and population could be ints, while lat/long could be floats.

**Comment by yaph** [comment]
Yes, I see no problem with that, this should be done in geonamescache/scripts/cities.py when the data is fetched. You want to submit a pull request?
